# This file disables Dependabot in favor of Renovate
# Keep this file to explicitly disable Dependabot

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
